=== brunomrcabral/Structured-Document-Processing/Part 1/XSD/livro_de_receitas.xsd
<?xml version="1.0" encoding="UTF-8"?>

<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="livro_de_receitas"
	xmlns:tns="livro_de_receitas" elementFormDefault="qualified">

	<element name="livro_de_receitas" type="tns:livro_de_receitas" />

	<complexType name="livro_de_receitas">
		<sequence>
			<element name="cabeçalho" type="tns:cabeçalho" maxOccurs="1" minOccurs="1" />
			<element name="parte" type="tns:parte" maxOccurs='unbounded' minOccurs="1" />
		</sequence>
	</complexType>


	<complexType name="cabeçalho">
		<sequence>
			<element name="titulo_do_conjunto_de_receitas" type="string"
				minOccurs="1" maxOccurs='unbounded' />
			<element name="autor" type="string" minOccurs="1" maxOccurs='unbounded' />
			<element name="data_publicaçao" type="date" minOccurs="1" maxOccurs="1" />
			<element name="resumo" type="string" minOccurs="0" maxOccurs="1" />
		</sequence>
	</complexType>



	<complexType name="parte">
		<sequence>
			<element name="titulo" type="string" minOccurs="1" maxOccurs="1" />
			<element name="introducao" type="string" minOccurs="0" maxOccurs="1" />
			<element name="url" type="tns:url" minOccurs="0" maxOccurs="1" />
			<element name="seccao" type="tns:seccao" minOccurs="0" maxOccurs='unbounded' />
		</sequence>
		<attribute use="required" name="tipo" type="ID" />
	</complexType>



	<complexType name="seccao">
		<sequence>
			<element name="titulo" type="string" minOccurs="1" maxOccurs="1" />
			<element name="introducao" type="string" minOccurs="0" maxOccurs="1" />
			<element name="url" type="tns:url" minOccurs="0" maxOccurs="1" />
			<element name="sub_seccao" type="tns:sub_seccao" minOccurs="0" maxOccurs='unbounded' />
		</sequence>
		<attribute use="required" name="tipo" type="ID" />
	</complexType>


	<complexType name="sub_seccao">
		<sequence>
			<element name="titulo" type="string" minOccurs="1" maxOccurs="1" />
			<element name="introducao" type="string" minOccurs="0" maxOccurs="1" />
			<element name="url" type="tns:url" minOccurs="0" maxOccurs="1" />
			<element name="receita" type="tns:receita" minOccurs="1" maxOccurs='unbounded' />
		</sequence>
		<attribute use="required" name="tipo" type="ID" />
	</complexType>


	<complexType name="receita">
		<sequence>
			<element name="ingredientes" type="tns:ingredientes" minOccurs="1" maxOccurs="1" />
			<element name="nome" type="string" minOccurs="1" maxOccurs="1" />
			<element name="tempo" type="string" minOccurs="0" maxOccurs="1" />
			<element name="calorias" type="positiveInteger" minOccurs="0" maxOccurs="1" />
			<element name="url" type="tns:url" minOccurs="0" maxOccurs="1" />
			<element name="descriçao" type="tns:descriçao" minOccurs="1" maxOccurs="1" />
		</sequence>

		<attribute name="id_receita" type="ID" use="required" />
		<attribute name="custo" use="optional">
			<simpleType>
				<restriction base="string">
					<pattern value="barato|médio|caro" />
				</restriction>
			</simpleType>
		</attribute>
		<attribute name="dificuldade" use="optional">
			<simpleType>
				<restriction base="string">
					<pattern value="fácil|médio|difícil" />
				</restriction>
			</simpleType>
		</attribute>
		<attribute name="categoria" type="string" use="optional" />
	</complexType>


	<complexType name="ingredientes">
		<sequence>
			<element name="ingrediente" type="tns:ingrediente" minOccurs="1" maxOccurs='unbounded' />
		</sequence>
	</complexType>


	<complexType name="ingrediente">
		<sequence>
			<element name="nome" type="string" minOccurs="1" maxOccurs="1" />
			<element name="quantidade" type="float" minOccurs="0" maxOccurs="1" />
			<element name="unidade" type="string" minOccurs="0" maxOccurs="1" />
		</sequence>
		<attribute name="id_ingrediente" type="ID" use="required" />
	</complexType>


	<complexType name="descriçao">
		<choice>
			<element name="passos" type="tns:passos" />
			<element name="texto" type="tns:texto" />

		</choice>
	</complexType>


	<complexType name="passos">
		<sequence>
			<element name="passo" type="tns:passos" minOccurs="1" maxOccurs='unbounded' />
		</sequence>
	</complexType>


	<complexType name="passo" mixed="true">
		<all>
			<element name="url" type="tns:url" minOccurs="0" />
			<element name="ref_ingrediente" type="tns:ref_ingrediente" minOccurs="0" />
			<element name="ref_receita" type="tns:ref_receita" minOccurs="0" />
		</all>
	</complexType>


	<complexType name="texto" mixed="true">
		<all>
			<element name="url" type="tns:url" minOccurs="0" />
			<element name="ref_ingrediente" type="tns:ref_ingrediente" minOccurs="0" />
			<element name="ref_receita" type="tns:ref_receita" minOccurs="0" />
		</all>
	</complexType>


	<complexType name="url">
		<attribute name="url" type="anyURI" use="required" />
	</complexType>

	<complexType name="ref_ingrediente">
		<attribute name="id_ingrediente" type="IDREF" use="required" />
	</complexType>

	<complexType name="ref_receita">
		<attribute name="id_receita" type="IDREF" use="required" />
	</complexType>

</schema>

=== brunomrcabral/Structured-Document-Processing/Part 1/XSD/xsd_livro_de_receitas.xml
<?xml version="1.0" encoding="UTF-8"?>

<tns:livro_de_receitas xmlns:tns="livro_receitas"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="livro_de_receitas livro_de_receitas.xsd">

	<tns:cabeçalho>
		<tns:titulo_do_conjunto_de_receitas>Cozinha Regional Portuguesa - Carnes</tns:titulo_do_conjunto_de_receitas>
		<tns:autor>Bruno Cabral</tns:autor>
		<tns:data_publicaçao>11-10-2006</tns:data_publicaçao>
		<tns:resumo>Livro de receitas simples, para qualquer pessoa.</tns:resumo>
	</tns:cabeçalho>


	<tns:parte tipo="pratos">
		<tns:titulo>Prato Principal</tns:titulo>
		<tns:introducao />
		<tns:url url="http://www.blabla.pt/prato_principal.png" />

		<tns:seccao tipo="carnes">
			<tns:titulo>Prato de Carne</tns:titulo>
			<tns:introducao>Pratos confecionados usando carne.</tns:introducao>
			<tns:url />

			<tns:sub_seccao tipo="porco">
				<tns:titulo>Prato com Porco</tns:titulo>
				<tns:introducao>Usando carne de porco como ingredente principal.</tns:introducao>
				<tns:url />

				<tns:receita id_receita="carne_porco_alentejana" dificuldade="médio" custo="caro" categoria="prato">
					<tns:ingredientes>
						<tns:ingrediente id_ingrediente="carne_porco">
							<tns:nome>Carne de Porco</tns:nome>
							<tns:quantidade>1.250</tns:quantidade>
							<tns:unidade>Kg</tns:unidade>
						</tns:ingrediente>

						<tns:ingrediente id_ingrediente="ameijoas">
							<tns:nome>Ameijoas</tns:nome> <!-- Ver como repersentar o ê -->
							<tns:quantidade>1</tns:quantidade>
							<tns:unidade>Kg</tns:unidade>
						</tns:ingrediente>

						<tns:ingrediente id_ingrediente="vinho_branco">
							<tns:nome>Vinho Branco </tns:nome>
							<tns:quantidade>1</tns:quantidade>
							<tns:unidade>Copo</tns:unidade>
						</tns:ingrediente>

						<tns:ingrediente id_ingrediente="batata">
							<tns:nome>Batatas</tns:nome>
							<tns:quantidade>1</tns:quantidade>
							<tns:unidade>Kg</tns:unidade>
						</tns:ingrediente>

						<tns:ingrediente id_ingrediente="banha">
							<tns:nome>Banha</tns:nome>
							<tns:quantidade>2</tns:quantidade>
							<tns:unidade>Colheres</tns:unidade>
						</tns:ingrediente>
					</tns:ingredientes>

					<tns:nome>Carne de Porco à Alentejana</tns:nome>
					<tns:tempo>Médio</tns:tempo>
					<tns:calorias>73259</tns:calorias>
					<tns:url url="http://www.blabla.pt/carne_alentejana.png" />

					<tns:descriçao>
						<tns:passos>
							<tns:passo>Cortar a carne<tns:ref_ingrediente id_ingrediente="carne_porco" />.</tns:passo>
							<tns:passo>Crie um refugado juntando o vinho branco<tns:ref_ingrediente id_ingrediente="vinho_branco" /> à carne.<tns:ref_ingrediente id_ingrediente="carne_porco" /><tns:url url="http://www.blabla.pt/imagem_refugado.png" /></tns:passo>
							<tns:passo>Ponha as ameijoas<tns:ref_ingrediente id_ingrediente="ameijoas" />de molho em água com sal de seguida cozinhe-as até estasabrirem.</tns:passo>
							<tns:passo>Aqueça a banha<tns:ref_ingrediente id_ingrediente="banha" />e ao mesmo tempo corte e frite as batatas.<tns:ref_ingrediente id_ingrediente="batatas" /></tns:passo>
							<tns:passo>Misture todos os ingredientes e sirva.<tns:url url="http://www.blabla.pt/carne_alentejana.png" /></tns:passo>
						</tns:passos>
					</tns:descriçao>

				</tns:receita>
			</tns:sub_seccao>

			<tns:sub_seccao tipo="vaca">
				<tns:titulo>Prato de Vaca </tns:titulo>
				<tns:introducao>Usando carne de vaca como ingrediente principal</tns:introducao>


				<tns:receita id_receita="carne_a_jardineira" dificuldade="díficil" custo="barato" categoria="prato">
					<tns:ingredientes>
						<tns:ingrediente id_ingrediente="carne_vaca">
							<tns:nome>Carne de Vaca</tns:nome>
							<tns:quantidade>2</tns:quantidade>
							<tns:unidade>Kg</tns:unidade>
						</tns:ingrediente>
					</tns:ingredientes>

					<tns:nome>Carne à Jardineira</tns:nome>
					<tns:tempo>Rápido</tns:tempo>
					<tns:calorias>2358426</tns:calorias>
					<tns:url url="http://www.blabla.pt/carne_de_vaca.png" />

					<tns:descriçao>
						<tns:texto>Metodo de preparação igual ao da carne de porco à alentejana<tns:ref_receita id_receita="carne_porco_alentejana" />basta apenas trocar o uso de carne de porco<tns:ref_ingrediente id_ingrediente="carne_porco" />por carne de vaca<tns:ref_ingrediente ingrediente="carne_vaca" /></tns:texto>
					</tns:descriçao>

				</tns:receita>

			</tns:sub_seccao>

		</tns:seccao>
	</tns:parte>


</tns:livro_de_receitas>
